--------------------------------------------------------
--  File created - Friday-April-20-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASKS
--------------------------------------------------------
/*
  CREATE TABLE "TASKS" ("TASK_ID" NUMBER(6,0), "TASK_NAME" VARCHAR2(255), "COST" NUMBER(6,0), "BUDGET" NUMBER(6,0), "ASSIGNED_TO" NUMBER(6,0), "PROJECT_ID" NUMBER(6,0)) ;
*/
REM INSERTING into TASKS
SET DEFINE OFF;
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (1,'HR SOFTWARE NEEDS UPGRADE',3000,3500,203,1);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (2,'APPLY BILLING SYSTEM UPDATES',500,500,203,1);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (3,'INVESTIGATE NEW VIRUS PROTECTION SOFTWARE',150,200,105,1);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (4,'ARRANGE FOR HOLIDAY COVERAGE',50,0,203,1);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (5,'COMPLETE PLAN',200,200,103,2);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (6,'CHECK SOFTWARE LICENSES',100,100,108,2);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (7,'GET RFPS FOR NEW SERVER',50,100,108,2);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (8,'PURCHASE BACKUP SERVER',2000,2400,108,2);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (9,'COMPLETE QUESTIONAIRE',350,400,110,3);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (10,'REVIEW WITH LEGAL',220,230,108,3);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (11,'PLAN ROLLOUT SCHEDULE',100,110,110,3);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (12,'DETERMINE HOST SERVER',75,100,101,4);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (13,'CHECK SOFTWARE LICENSES',120,120,106,4);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (14,'PURCHASE ADDITIONAL SOFTWARE LICENSES',0,1200,106,4);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (15,'DEVELOP WEB PAGES',750,1000,104,4);
Insert into TASKS (TASK_ID,TASK_NAME,COST,BUDGET,ASSIGNED_TO,PROJECT_ID) values (16,'PLAN ROLLOUT SCHEDULE',120,120,106,4);
--------------------------------------------------------
--  DDL for Index TASKS PK
--------------------------------------------------------
/*
  CREATE UNIQUE INDEX "TASKS PK" ON "TASKS" ("TASK_ID") ;
/
--------------------------------------------------------
--  Constraints for Table TASKS
--------------------------------------------------------

  ALTER TABLE "TASKS" ADD CONSTRAINT "TASKS PK" PRIMARY KEY ("TASK_ID") ENABLE;
  ALTER TABLE "TASKS" MODIFY ("TASK_ID" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Ref Constraints for Table TASKS
--------------------------------------------------------

  ALTER TABLE "TASKS" ADD CONSTRAINT "RELATION_5" FOREIGN KEY ("ASSIGNED_TO") REFERENCES "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
  ALTER TABLE "TASKS" ADD CONSTRAINT "RELATION_6" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECTS" ("PROJECT_ID") ENABLE;
/
*/
