CREATE TABLE  "GANTT_INFO" 
   (    "ID" NUMBER, 
    "TASKS" VARCHAR2(4000), 
    "START_DATE" DATE, 
    "END_DATE" DATE, 
    "STATUS" NUMBER, 
    "DETAILS" VARCHAR2(4000), 
    "EMP_ID" NUMBER, 
    "PARENT_ID" NUMBER
   )
/
