-- Generated by Oracle SQL Developer Data Modeler 3.1.1.703
--   at:        2012-04-19 11:36:53 PDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE PROJECTS 
    ( 
     PROJECT_ID NUMBER (6)  NOT NULL , 
     PROJECT_NAME VARCHAR2 (100) , 
     PROJECT_START_DATE DATE , 
     PROJECT_END_DATE DATE , 
     PROJECT_DEPT NUMBER (4) , 
     STATUS VARCHAR2 (30) 
    ) 
    LOGGING 
;


ALTER TABLE PROJECTS 
    ADD CONSTRAINT PROJECTS_PK PRIMARY KEY ( PROJECT_ID  ) ;


CREATE TABLE TASKS 
    ( 
     TASK_ID NUMBER (6)  NOT NULL , 
     TASK_NAME VARCHAR2 (255) , 
     COST NUMBER (6) , 
     BUDGET NUMBER (6) , 
     ASSIGNED_TO NUMBER (6) , 
     PROJECT_ID NUMBER (6) 
    ) 
    LOGGING 
;


ALTER TABLE TASKS 
    ADD CONSTRAINT "TASKS PK" PRIMARY KEY ( TASK_ID  ) ;


ALTER TABLE HR.DEPARTMENTS ADD 
    ( 
     COST_CENTER VARCHAR2 (25) 
    ) 
;


ALTER TABLE PROJECTS 
    ADD CONSTRAINT PROJECTS_DEPARTMENTS_FK FOREIGN KEY 
    ( 
     PROJECT_DEPT
    ) 
    REFERENCES HR.DEPARTMENTS 
    ( 
     DEPARTMENT_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE TASKS 
    ADD CONSTRAINT Relation_5 FOREIGN KEY 
    ( 
     ASSIGNED_TO
    ) 
    REFERENCES HR.EMPLOYEES 
    ( 
     EMPLOYEE_ID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE TASKS 
    ADD CONSTRAINT Relation_6 FOREIGN KEY 
    ( 
     PROJECT_ID
    ) 
    REFERENCES PROJECTS 
    ( 
     PROJECT_ID
    ) 
    NOT DEFERRABLE 
;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             0
-- CREATE VIEW                              0
-- ALTER TABLE                              6
-- ALTER INDEX                              0
-- DROP TABLE                               0
-- DROP INDEX                               0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- DROP VIEW                                0

-- 
-- ERRORS                                   0
-- WARNINGS                                 0
